version: "3.4"

services:
  backend-dev:
    container_name: backend-dev
    build:
      context: .
      target: build
      dockerfile: ./Dockerfile
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules

  # backend-prod:
  #   container_name: backend-prod
  #   build:
  #     context: .
  #     target: prod
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
