version: '3.4'

services:
  dev:
    image: popular-repos-search
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: npm run dev
    ports:
      - 4000:4000
    # networks:
    #   - nesjs-network
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped
